# Generated by Django 3.2.5 on 2021-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberdata',
            name='total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
