# Generated by Django 3.2.5 on 2021-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0003_alter_numberdata_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberdata',
            name='number_one',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='number_two',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
