# Generated by Django 3.2.5 on 2021-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0004_auto_20210801_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberdata',
            name='total',
        ),
    ]
