# Generated by Django 3.2.5 on 2021-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answer', '0005_remove_numberdata_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberdata',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
